# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-4017-testserver/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg484-2
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/ec67/hdl
    /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/c2c6
    /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_quad_spi_0_0/netlist
    /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_quad_spi_0_1/netlist
  } {
      /home/test/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /home/test/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /home/test/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/ec67/hdl
    /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/c2c6
    /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_quad_spi_0_0/netlist
    /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_quad_spi_0_1/netlist
  } {
      /home/test/Projects/CameraZynq/CameraFPGA/gmax0505_streamer/edge_capture.v
      /home/test/Projects/CameraZynq/CameraFPGA/gmax0505_streamer/idelay2_wrapper.v
      /home/test/Projects/CameraZynq/CameraFPGA/gmax0505_streamer/ddr_deserialiser.v
      /home/test/Projects/CameraZynq/CameraFPGA/gmax0505_streamer/word_detector.v
      /home/test/Projects/CameraZynq/CameraFPGA/gmax0505_streamer/decoder.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/synth/sensor_inst_0.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/synth/top.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/hdl/top_wrapper.v
      /home/test/Projects/CameraZynq/CameraFPGA/gmax0505_streamer/bit_aligner.v
    }
      rt::read_verilog -include {
    /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/ec67/hdl
    /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/c2c6
    /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_quad_spi_0_0/netlist
    /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_quad_spi_0_1/netlist
  } {
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ipshared/e2ba/hdl/ltlib_v1_0_vl_rfs.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ipshared/a29c/hdl/xsdbs_v1_0_vl_rfs.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ipshared/ae90/hdl/xsdbm_v3_0_vl_rfs.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ipshared/0e59/hdl/ila_v6_2_syn_rfs.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ip/sensor_inst_0_ila_0_0/synth/sensor_inst_0_ila_0_0.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ipshared/217a/hdl/xlslice_v1_0_vl_rfs.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ip/sensor_inst_0_xlslice_0_0/synth/sensor_inst_0_xlslice_0_0.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ip/sensor_inst_0_xlslice_1_0/synth/sensor_inst_0_xlslice_1_0.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ip/sensor_inst_0_idelay2_wrapper_0_0/synth/sensor_inst_0_idelay2_wrapper_0_0.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ip/sensor_inst_0_ddr_deserialiser_0_0/synth/sensor_inst_0_ddr_deserialiser_0_0.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ip/sensor_inst_0_word_detector_0_0_1/synth/sensor_inst_0_word_detector_0_0.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ip/sensor_inst_0_decoder_0_0/synth/sensor_inst_0_decoder_0_0.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ip/sensor_inst_0_bit_aligner_0_0_1/synth/sensor_inst_0_bit_aligner_0_0.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ip/sensor_inst_0_bit_aligner_1_0/synth/sensor_inst_0_bit_aligner_1_0.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_processing_system7_0_0/synth/top_processing_system7_0_0.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/10ab/hdl/generic_baseblocks_v2_1_vl_rfs.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/ff9f/hdl/axi_register_slice_v2_1_vl_rfs.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/279e/hdl/axi_data_fifo_v2_1_vl_rfs.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/fb47/hdl/axi_crossbar_v2_1_vl_rfs.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_xbar_0/synth/top_xbar_0.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0_clk_wiz.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/d390/hdl/xlconstant_v1_1_vl_rfs.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_xlconstant_0_0/synth/top_xlconstant_0_0.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/147b/hdl/xlconcat_v2_1_vl_rfs.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_xlconcat_0_0/synth/top_xlconcat_0_0.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/a63f/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_auto_pc_0/synth/top_auto_pc_0.v
    }
      rt::read_vhdl -lib xpm /home/test/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_5 /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_gpio_v2_0_31 /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ipshared/6fbe/hdl/axi_gpio_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ip/sensor_inst_0_axi_gpio_0_0/synth/sensor_inst_0_axi_gpio_0_0.vhd
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ip/sensor_inst_0_util_ds_buf_0_0/util_ds_buf.vhd
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ip/sensor_inst_0_util_ds_buf_0_0/synth/sensor_inst_0_util_ds_buf_0_0.vhd
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ip/sensor_inst_0_util_ds_buf_1_0/synth/sensor_inst_0_util_ds_buf_1_0.vhd
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_gpio_0_0/synth/top_axi_gpio_0_0.vhd
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_rst_ps7_0_50M_0/synth/top_rst_ps7_0_50M_0.vhd
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_uartlite_0_0/synth/top_axi_uartlite_0_0.vhd
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_quad_spi_0_0/synth/top_axi_quad_spi_0_0.vhd
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_quad_spi_0_1/synth/top_axi_quad_spi_0_1.vhd
      /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_uartlite_0_1/synth/top_axi_uartlite_0_1.vhd
    }
      rt::read_vhdl -lib blk_mem_gen_v8_3_7 /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ipshared/1a4e/hdl/blk_mem_gen_v8_3_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_1_5 /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ipshared/1665/hdl/fifo_generator_v13_1_vhsyn_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_7 /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/bd/sensor_inst_0/ipshared/3c0c/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_9 /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/ac72/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_14 /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/408c/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib lib_pkg_v1_0_3 /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/56d9/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_srl_fifo_v1_0_3 /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/02c4/hdl/lib_srl_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_uartlite_v2_0_33 /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/df48/hdl/axi_uartlite_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib lib_fifo_v1_0_18 /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/1531/hdl/lib_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib dist_mem_gen_v8_0_14 /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/2ec6/hdl/dist_mem_gen_v8_0_vhsyn_rfs.vhd
      rt::read_vhdl -lib axi_quad_spi_v3_2_28 /home/test/Projects/CameraZynq/CameraFPGA/camera.gen/sources_1/bd/top/ipshared/98d8/hdl/axi_quad_spi_v3_2_rfs.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top_wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter linterFlow true
    rt::set_parameter synthReportEmptyAndUndriven false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-4017-testserver/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
