# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_gpio_0_0/top_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_gpio_0_0 || ORIG_REF_NAME==top_axi_gpio_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xbar_0/top_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xbar_0 || ORIG_REF_NAME==top_xbar_0} -quiet] -quiet

# IP: bd/top/ip/top_ps7_0_axi_periph_0/top_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ps7_0_axi_periph_0 || ORIG_REF_NAME==top_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_ps7_0_50M_0/top_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_ps7_0_50M_0 || ORIG_REF_NAME==top_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_uartlite_0_0/top_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_uartlite_0_0 || ORIG_REF_NAME==top_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_quad_spi_0_0/top_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_quad_spi_0_0 || ORIG_REF_NAME==top_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_clk_wiz_0_0 || ORIG_REF_NAME==top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_quad_spi_0_1/top_axi_quad_spi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_quad_spi_0_1 || ORIG_REF_NAME==top_axi_quad_spi_0_1} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_0_0/top_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_0_0 || ORIG_REF_NAME==top_xlconstant_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_uartlite_0_1/top_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_uartlite_0_1 || ORIG_REF_NAME==top_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_0/top_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_0 || ORIG_REF_NAME==top_auto_pc_0} -quiet] -quiet

# XDC: /home/test/Projects/CameraZynq/camera_program/src/submodules/CameraFPGA/camera.gen/sources_1/bd/top/top_ooc.xdc
