# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/test/Projects/CameraZynq/camera_program/src/submodules/CameraFPGA/camera.srcs/sources_1/bd/top/ip/top_axi_uartlite_0_0/top_axi_uartlite_0_0.xci
# IP: The module: 'top_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/test/Projects/CameraZynq/camera_program/src/submodules/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_uartlite_0_0/top_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/test/Projects/CameraZynq/camera_program/src/submodules/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_uartlite_0_0/top_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/test/Projects/CameraZynq/camera_program/src/submodules/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_uartlite_0_0/top_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/test/Projects/CameraZynq/camera_program/src/submodules/CameraFPGA/camera.srcs/sources_1/bd/top/ip/top_axi_uartlite_0_0/top_axi_uartlite_0_0.xci
# IP: The module: 'top_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/test/Projects/CameraZynq/camera_program/src/submodules/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_uartlite_0_0/top_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/test/Projects/CameraZynq/camera_program/src/submodules/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_uartlite_0_0/top_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/test/Projects/CameraZynq/camera_program/src/submodules/CameraFPGA/camera.gen/sources_1/bd/top/ip/top_axi_uartlite_0_0/top_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
