set_property IOSTANDARD LVCMOS33 [get_ports ETH_CLK25M]
set_property PACKAGE_PIN D21 [get_ports ETH_CLK25M]
set_property PACKAGE_PIN G22 [get_ports {ETH_NRST[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_NRST[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports USB_REFCLK]
set_property PACKAGE_PIN A22 [get_ports USB_REFCLK]
set_property IOSTANDARD LVCMOS33 [get_ports {USB_NRST[0]}]
set_property PACKAGE_PIN F22 [get_ports {USB_NRST[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_IN_tri_i[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_IN_tri_i[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_IN_tri_i[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_IN_tri_i[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_IN_tri_i[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_IN_tri_i[1]}]
set_property PACKAGE_PIN V5 [get_ports {FPGA_GPIO_IN_tri_i[0]}]
set_property PACKAGE_PIN AB2 [get_ports {FPGA_GPIO_IN_tri_i[1]}]
set_property PACKAGE_PIN AB4 [get_ports {FPGA_GPIO_IN_tri_i[2]}]
set_property PACKAGE_PIN V4 [get_ports {FPGA_GPIO_IN_tri_i[3]}]
set_property PACKAGE_PIN AB1 [get_ports {FPGA_GPIO_IN_tri_i[4]}]
set_property PACKAGE_PIN AB12 [get_ports {FPGA_GPIO_IN_tri_i[5]}]
set_property PACKAGE_PIN Y8 [get_ports {FPGA_GPIO_IN_tri_i[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_IN_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO_OUT_tri_o[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO_OUT_tri_o[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO_OUT_tri_o[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_OUT_tri_o[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_OUT_tri_o[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO_OUT_tri_o[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO_OUT_tri_o[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO_OUT_tri_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO_OUT_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO_OUT_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO_OUT_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO_OUT_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO_OUT_tri_o[0]}]
set_property PACKAGE_PIN D15 [get_ports {FPGA_GPIO_OUT_tri_o[1]}]
set_property PACKAGE_PIN Y4 [get_ports {FPGA_GPIO_OUT_tri_o[2]}]
set_property PACKAGE_PIN C15 [get_ports {FPGA_GPIO_OUT_tri_o[3]}]
set_property PACKAGE_PIN B15 [get_ports {FPGA_GPIO_OUT_tri_o[4]}]
set_property PACKAGE_PIN A16 [get_ports {FPGA_GPIO_OUT_tri_o[5]}]
set_property PACKAGE_PIN AB9 [get_ports {FPGA_GPIO_OUT_tri_o[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_OUT_tri_o[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_OUT_tri_o[2]}]
set_property PACKAGE_PIN E20 [get_ports {FPGA_GPIO_OUT_tri_o[7]}]
set_property PACKAGE_PIN E21 [get_ports {FPGA_GPIO_OUT_tri_o[8]}]
set_property PACKAGE_PIN E19 [get_ports {FPGA_GPIO_OUT_tri_o[9]}]
set_property PACKAGE_PIN U5 [get_ports {FPGA_GPIO_OUT_tri_o[10]}]
set_property PACKAGE_PIN U6 [get_ports {FPGA_GPIO_OUT_tri_o[11]}]
set_property PACKAGE_PIN F19 [get_ports {FPGA_GPIO_OUT_tri_o[12]}]
set_property PACKAGE_PIN E18 [get_ports {FPGA_GPIO_OUT_tri_o[13]}]
set_property PACKAGE_PIN D20 [get_ports {FPGA_GPIO_OUT_tri_o[14]}]
set_property PACKAGE_PIN R6 [get_ports {FPGA_GPIO_OUT_tri_o[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_OUT_tri_o[15]}]
set_property PACKAGE_PIN AB5 [get_ports {FPGA_GPIO_OUT_tri_o[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_OUT_tri_o[16]}]
set_property PACKAGE_PIN W7 [get_ports {FPGA_GPIO_OUT_tri_o[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_OUT_tri_o[17]}]
set_property PACKAGE_PIN AB11 [get_ports PSS_PMC_UART_txd]
set_property PACKAGE_PIN AB10 [get_ports PSS_PMC_UART_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports PSS_PMC_UART_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports PSS_PMC_UART_txd]
set_property PACKAGE_PIN E16 [get_ports DISP_SPI_SCLK]
set_property PACKAGE_PIN F16 [get_ports DISP_SPI_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP_SPI_NCS[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports DISP_SPI_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports DISP_SPI_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports {BADC_SPI_NCS[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports BADC_SPI_MISO]
set_property IOSTANDARD LVCMOS18 [get_ports BADC_SPI_SCLK]
set_property PACKAGE_PIN P21 [get_ports BADC_SPI_MISO]
set_property PACKAGE_PIN R19 [get_ports BADC_SPI_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports ESP_PSS_UART_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports ESP_PSS_UART_txd]
set_property PACKAGE_PIN B22 [get_ports ESP_PSS_UART_txd]
set_property PACKAGE_PIN C22 [get_ports ESP_PSS_UART_rxd]


set_property IOSTANDARD LVCMOS18 [get_ports SDIO_1_0_cdn]
set_property IOSTANDARD LVCMOS18 [get_ports SDIO_1_0_wp]
set_property PACKAGE_PIN Y10 [get_ports SDIO_1_0_cdn]
set_property PACKAGE_PIN AA9 [get_ports SDIO_1_0_wp]

set_property PACKAGE_PIN P20 [get_ports {FPGA_GPIO_OUT_tri_o[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_OUT_tri_o[19]}]
set_property PACKAGE_PIN E15 [get_ports {FPGA_GPIO_OUT_tri_o[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FPGA_GPIO_OUT_tri_o[18]}]
set_property PACKAGE_PIN F17 [get_ports {BADC_SPI_NCS[0]}]
set_property PACKAGE_PIN F18 [get_ports {DISP_SPI_NCS[0]}]

set_property PACKAGE_PIN M22 [get_ports SENSOR_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports SENSOR_CLK]

set_property PACKAGE_PIN Y21 [get_ports {FPGA_GPIO_IN_tri_i[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_IN_tri_i[7]}]
set_property PACKAGE_PIN U22 [get_ports {FPGA_GPIO_OUT_tri_o[20]}]
set_property PACKAGE_PIN U19 [get_ports {FPGA_GPIO_OUT_tri_o[21]}]
set_property PACKAGE_PIN T22 [get_ports {FPGA_GPIO_OUT_tri_o[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_OUT_tri_o[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_OUT_tri_o[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_OUT_tri_o[20]}]

set_property PACKAGE_PIN D16 [get_ports {FPGA_GPIO_OUT_tri_o[0]}]



set_property PACKAGE_PIN W5 [get_ports {FPGA_GPIO_IN_tri_i[8]}]
set_property PACKAGE_PIN Y5 [get_ports {FPGA_GPIO_IN_tri_i[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_IN_tri_i[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_IN_tri_i[9]}]
set_property PACKAGE_PIN Y6 [get_ports {FPGA_GPIO_OUT_tri_o[23]}]
set_property PACKAGE_PIN W6 [get_ports {FPGA_GPIO_OUT_tri_o[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_OUT_tri_o[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO_OUT_tri_o[24]}]


# Sensor LVDS inputs
# Clock
set_property PACKAGE_PIN N19 [get_ports {sen_ddr_clk_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_ddr_clk_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_ddr_clk_clk_p[0]}]
create_clock -period 5.000 [get_ports {sen_ddr_clk_clk_p[0]}]
set_input_jitter [get_clocks -of_objects [get_ports {sen_ddr_clk_clk_p[0]}]] 0.100

# Data inputs
set_property PACKAGE_PIN J20 [get_ports {sen_data_0_0_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_data_0_0_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_data_0_0_clk_p[0]}]
set_property PACKAGE_PIN J21 [get_ports {sen_data_1_0_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_data_1_0_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_data_1_0_clk_p[0]}]
set_property PACKAGE_PIN J16 [get_ports {sen_data_2_0_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_data_2_0_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_data_2_0_clk_p[0]}]
set_property PACKAGE_PIN J18 [get_ports {sen_data_3_0_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_data_3_0_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_data_3_0_clk_p[0]}]
set_property PACKAGE_PIN L21 [get_ports {sen_data_4_0_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_data_4_0_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_data_4_0_clk_p[0]}]
set_property PACKAGE_PIN M15 [get_ports {sen_data_5_0_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_data_5_0_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_data_5_0_clk_p[0]}]
set_property PACKAGE_PIN L18 [get_ports {sen_data_6_0_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_data_6_0_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_data_6_0_clk_p[0]}]
set_property PACKAGE_PIN K19 [get_ports {sen_data_7_0_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_data_7_0_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_data_7_0_clk_p[0]}]
set_property PACKAGE_PIN T16 [get_ports {sen_data_8_0_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_data_8_0_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_data_8_0_clk_p[0]}]
set_property PACKAGE_PIN N22 [get_ports {sen_data_9_0_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_data_9_0_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_data_9_0_clk_p[0]}]
set_property PACKAGE_PIN N17 [get_ports {sen_data_10_0_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_data_10_0_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_data_10_0_clk_p[0]}]
set_property PACKAGE_PIN L17 [get_ports {sen_data_11_0_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_data_11_0_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_data_11_0_clk_p[0]}]
set_property PACKAGE_PIN R20 [get_ports {sen_data_12_0_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_data_12_0_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_data_12_0_clk_p[0]}]
set_property PACKAGE_PIN R18 [get_ports {sen_data_13_0_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_data_13_0_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_data_13_0_clk_p[0]}]
set_property PACKAGE_PIN P16 [get_ports {sen_data_14_0_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_data_14_0_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_data_14_0_clk_p[0]}]
set_property PACKAGE_PIN N15 [get_ports {sen_data_15_0_clk_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {sen_data_15_0_clk_p[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {sen_data_15_0_clk_p[0]}]
